# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BIC <- function(obj, y, z, x, tol = 1e-4) {
    .Call('_Spgr_BIC', PACKAGE = 'Spgr', obj, y, z, x, tol)
}

BICx <- function(obj, y, x, tol = 1e-4) {
    .Call('_Spgr_BICx', PACKAGE = 'Spgr', obj, y, x, tol)
}

BICr <- function(obj, indexy, y, z, x, tol = 1e-4) {
    .Call('_Spgr_BICr', PACKAGE = 'Spgr', obj, indexy, y, z, x, tol)
}

BICrx <- function(obj, indexy, y, x, tol = 1e-4) {
    .Call('_Spgr_BICrx', PACKAGE = 'Spgr', obj, indexy, y, x, tol)
}

BICc <- function(obj, y, z, x, c0 = 0.2, tol = 1e-4) {
    .Call('_Spgr_BICc', PACKAGE = 'Spgr', obj, y, z, x, c0, tol)
}

BICcx <- function(obj, y, x, c0 = 0.2, tol = 1e-4) {
    .Call('_Spgr_BICcx', PACKAGE = 'Spgr', obj, y, x, c0, tol)
}

BICcr <- function(obj, indexy, y, z, x, c0 = 0.2, tol = 1e-4) {
    .Call('_Spgr_BICcr', PACKAGE = 'Spgr', obj, indexy, y, z, x, c0, tol)
}

BICcrx <- function(obj, indexy, y, x, c0 = 0.2, tol = 1e-4) {
    .Call('_Spgr_BICcrx', PACKAGE = 'Spgr', obj, indexy, y, x, c0, tol)
}

BIClog <- function(obj, y, z, x, tol = 1e-4) {
    .Call('_Spgr_BIClog', PACKAGE = 'Spgr', obj, y, z, x, tol)
}

BIClogx <- function(obj, y, x, tol = 1e-4) {
    .Call('_Spgr_BIClogx', PACKAGE = 'Spgr', obj, y, x, tol)
}

BIClogr <- function(obj, indexy, y, z, x, tol = 1e-4) {
    .Call('_Spgr_BIClogr', PACKAGE = 'Spgr', obj, indexy, y, z, x, tol)
}

BIClogrx <- function(obj, indexy, y, x, tol = 1e-4) {
    .Call('_Spgr_BIClogrx', PACKAGE = 'Spgr', obj, indexy, y, x, tol)
}

Spgr <- function(y, z, x, weights, betam0, nu = 1, gam = 3, lam = 0.5, maxiter = 1000L, tolabs = 1e-4, tolrel = 1e-2) {
    .Call('_Spgr_Spgr', PACKAGE = 'Spgr', y, z, x, weights, betam0, nu, gam, lam, maxiter, tolabs, tolrel)
}

selectlam <- function(y, z, x, weights, lamv, betam0, nu = 1, gam = 3, maxiter = 1000L, tolabs = 1e-4, tolrel = 1e-2) {
    .Call('_Spgr_selectlam', PACKAGE = 'Spgr', y, z, x, weights, lamv, betam0, nu, gam, maxiter, tolabs, tolrel)
}

Spgr_penalty <- function(y, z, x, rho, matpen, weights, betam0, nu = 1, gam = 3, lam = 0.5, maxiter = 1000L, tolabs = 1e-4, tolrel = 1e-2) {
    .Call('_Spgr_Spgr_penalty', PACKAGE = 'Spgr', y, z, x, rho, matpen, weights, betam0, nu, gam, lam, maxiter, tolabs, tolrel)
}

Spgrr <- function(indexy, y, z, x, weights, betam0, nu = 1, gam = 3, lam = 0.5, maxiter = 1000L, tolabs = 1e-4, tolrel = 1e-2) {
    .Call('_Spgr_Spgrr', PACKAGE = 'Spgr', indexy, y, z, x, weights, betam0, nu, gam, lam, maxiter, tolabs, tolrel)
}

Spgrrx <- function(indexy, y, x, weights, betam0, nu = 1, gam = 3, lam = 0.5, maxiter = 1000L, tolabs = 1e-4, tolrel = 1e-2) {
    .Call('_Spgr_Spgrrx', PACKAGE = 'Spgr', indexy, y, x, weights, betam0, nu, gam, lam, maxiter, tolabs, tolrel)
}

Spgrwise_lasso <- function(y, z, x, weights, betam0, nu = 1, lam = 0.5, maxiter = 1000L, tolabs = 1e-4, tolrel = 1e-2) {
    .Call('_Spgr_Spgrwise_lasso', PACKAGE = 'Spgr', y, z, x, weights, betam0, nu, lam, maxiter, tolabs, tolrel)
}

Spgrwise_scad <- function(y, z, x, weights, betam0, nu = 1, gam = 3, lam = 0.5, maxiter = 1000L, tolabs = 1e-4, tolrel = 1e-2) {
    .Call('_Spgr_Spgrwise_scad', PACKAGE = 'Spgr', y, z, x, weights, betam0, nu, gam, lam, maxiter, tolabs, tolrel)
}

Spgrwise_rep_lasso <- function(indexy, y, z, x, weights, betam0, nu = 1, lam = 0.5, maxiter = 1000L, tolabs = 1e-4, tolrel = 1e-2) {
    .Call('_Spgr_Spgrwise_rep_lasso', PACKAGE = 'Spgr', indexy, y, z, x, weights, betam0, nu, lam, maxiter, tolabs, tolrel)
}

Spgrwise_rep_scad <- function(indexy, y, z, x, weights, betam0, nu = 1, gam = 3, lam = 0.5, maxiter = 1000L, tolabs = 1e-4, tolrel = 1e-2) {
    .Call('_Spgr_Spgrwise_rep_scad', PACKAGE = 'Spgr', indexy, y, z, x, weights, betam0, nu, gam, lam, maxiter, tolabs, tolrel)
}

Spgrx <- function(y, x, weights, betam0, nu = 1, gam = 3, lam = 0.5, maxiter = 1000L, tolabs = 1e-4, tolrel = 1e-2) {
    .Call('_Spgr_Spgrx', PACKAGE = 'Spgr', y, x, weights, betam0, nu, gam, lam, maxiter, tolabs, tolrel)
}

selectlamx <- function(y, x, weights, lamv, betam0, nu = 1, gam = 3, maxiter = 1000L, tolabs = 1e-4, tolrel = 1e-2) {
    .Call('_Spgr_selectlamx', PACKAGE = 'Spgr', y, x, weights, lamv, betam0, nu, gam, maxiter, tolabs, tolrel)
}

cal_initial0 <- function(y, z, x, lam0 = 0.0001) {
    .Call('_Spgr_cal_initial0', PACKAGE = 'Spgr', y, z, x, lam0)
}

cal_initial <- function(y, z, x, lam0 = 0.0001) {
    .Call('_Spgr_cal_initial', PACKAGE = 'Spgr', y, z, x, lam0)
}

cal_initialx <- function(y, x, lam0 = 0.0001) {
    .Call('_Spgr_cal_initialx', PACKAGE = 'Spgr', y, x, lam0)
}

cal_initialr <- function(indexy, y, z, x, lam0 = 0.0001) {
    .Call('_Spgr_cal_initialr', PACKAGE = 'Spgr', indexy, y, z, x, lam0)
}

cal_initialrx <- function(indexy, y, x, lam0 = 0.0001) {
    .Call('_Spgr_cal_initialrx', PACKAGE = 'Spgr', indexy, y, x, lam0)
}

cal_initialr2 <- function(indexy, y, z, x, K0, lam0 = 0.0001) {
    .Call('_Spgr_cal_initialr2', PACKAGE = 'Spgr', indexy, y, z, x, K0, lam0)
}

cal_initialrx2 <- function(indexy, y, x, K0, lam0 = 0.0001) {
    .Call('_Spgr_cal_initialrx2', PACKAGE = 'Spgr', indexy, y, x, K0, lam0)
}

getgroup <- function(deltam, n, tol = 1e-4) {
    .Call('_Spgr_getgroup', PACKAGE = 'Spgr', deltam, n, tol)
}

ngetgroup <- function(b2value, n, tol = 1e-3) {
    .Call('_Spgr_ngetgroup', PACKAGE = 'Spgr', b2value, n, tol)
}

getorder <- function(Cmat) {
    .Call('_Spgr_getorder', PACKAGE = 'Spgr', Cmat)
}

